(function(c){function j(a){return a.replace(/^\s+|\s+$/g,"")}function m(){if(!c.publishableKey)throw"No Publishable API Key: Call Stripe.setPublishableKey to provide your key.";}var d=null,k={};"undefined"!==typeof window&&!window.JSON&&(window.JSON={});(function(){if("function"!==typeof JSON.parse)JSON.parse=function(a,b){function g(a,e){var d,c,f=a[e];if(f&&"object"===typeof f)for(d in f)Object.hasOwnProperty.call(f,d)&&(c=g(f,d),void 0!==c?f[d]=c:delete f[d]);return b.call(a,e,f)}var e=RegExp("[\\u0000\\u00ad\\u0600-\\u0604\\u070f\\u17b4\\u17b5\\u200c-\\u200f\\u2028-\\u202f\\u2060-\\u206f\\ufeff\\ufff0-\\uffff]",
"g"),a=""+a;e.lastIndex=0;e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof b?g({"":e},""):e;throw new SyntaxError("JSON.parse");}})();var t=function(a){function b(){c=null;var a=document.getElementsByTagName("body")[0],
b=document.createElement("iframe");l="stripeFrame"+(new Date).getTime();p=h.apiURL+"/js/v1/apitunnel.html";var i=p+"#"+encodeURIComponent(window.location.href);b.setAttribute("src",i);b.setAttribute("name",l);b.setAttribute("id",l);b.setAttribute("frameborder","0");b.setAttribute("scrolling","no");b.setAttribute("allowtransparency","true");b.setAttribute("width",0);b.setAttribute("height",0);b.setAttribute("style","position:absolute;top:0;left:0;width:0;height:0");i=function(){c=window.frames[l];
d()};b.attachEvent?b.attachEvent("onload",i):b.onload=i;a.appendChild(b)}function d(){if(c){var b=n.length;if(0<b){for(var e=0;e<b;++e){var i=n[e].message,q=i.id;o[q]=n[e].callback;a.postMessage(i,h.apiURL,p,c);f[q]=window.setTimeout(function(a){o[a](504,{error:{message:"There was an error processing your card"}});delete o[a];delete f[a]},6E4,q)}n=[]}}}if("undefined"===typeof a){var a={},e=function(a){if("undefined"===typeof a){var a={},b=function(){var a={};a.serialize=function(b,e){var d=[],c;for(c in b)if(b.hasOwnProperty(c)){var g=
e?e+"["+c+"]":c,f=b[c];d.push("object"==typeof f?a.serialize(f,g):encodeURIComponent(g)+"="+encodeURIComponent(f))}return d.join("&")};a.deserialize=function(a){for(var b={},a=a.split("&"),e=a.length,c=null,d=null,i=0;i<e;++i){d=a[i].split("=");d[0]=decodeURIComponent(d[0]);d[1]=decodeURIComponent(d[1]);for(var g=d[0],c=[],f=-1;-1!==(f=g.indexOf("["));)c.push(g.substr(f,g.indexOf("]")-f+1)),g=g.substr(g.indexOf("]")+1);if(0===c.length)b[d[0]]=d[1];else{f=d[0].substr(0,d[0].indexOf("["));"undefined"===
typeof b[f]&&(b[f]={});for(var g=b[f],s=c.length,h=0;h<s-1;++h)f=c[h].substr(1,c[h].length-2),"undefined"===typeof g[f]&&(g[f]={}),g=g[f];c=c[s-1];f=c.substr(1,c.length-2);g[f]=d[1]}}return b};return a};"undefined"!==typeof a?a=b():exports.createSerializer=b}b={};b.postMessage=function(b,c,d,e){if("undefined"!==typeof window)b=a.serialize(b),"undefined"===typeof window.postMessage?e.location.href=d+"#"+ +new Date+Math.floor(1E3*Math.random())+"&"+b:e.postMessage(b,c)};b.receiveMessage=function(b,
c){if("undefined"!==typeof window)if(window.postMessage)attachedCallback=function(d){if(d.origin.toLowerCase()!==c.toLowerCase())return!1;b(a.deserialize(d.data))},window.addEventListener?window.addEventListener("message",attachedCallback,!1):window.attachEvent("onmessage",attachedCallback);else{var d=window.location.hash;setInterval(function(){var c=window.location.hash,e=/^#?\d+&/;if(c!==d&&e.test(c))d=c,window.location.hash="",b(a.deserialize(c.replace(e,"")))},100)}};return b};"undefined"!==typeof a?
a=e():exports.createXD=e}var c=null,n=[],k=0,o={},f={},j=!1,l,p,h={apiURL:"https://api.stripe.com",onMessage:function(a){var b=a.id,c=null,c=null===a.response||""===a.response?{error:{message:"There was an error processing your card"}}:JSON.parse(a.response);o[b](parseInt(a.status),c);window.clearTimeout(f[b]);delete o[b];delete f[b]}},m=!1,r=function(){b();m||(a.receiveMessage(h.onMessage,h.apiURL),m=!0)};h.init=function(){if(!l||!document.getElementById(l))"undefined"!==typeof document&&document&&
document.body?r():"undefined"!==typeof window&&window&&!j&&(window.addEventListener?window.addEventListener("load",r,!1):window.attachEvent&&window.attachEvent("onload",r)),j=!0};h.callAPI=function(a,b,c,e,f){if("POST"!==a&&"GET"!==a&&"DELETE"!==a)throw"You can only call the API with POST, GET or DELETE";h.init();var j=(k++).toString();n.push({message:{id:j,method:a,url:"/v1/"+b,params:c,key:e},callback:f});d()};return h};"undefined"!==typeof k?k=t():exports.createTransport=t;c.transport=k;c.validateCardNumber=
function(a){var a=a.replace(/\s+|-/g,""),b;if(b=10<=a.length)if(b=16>=a.length)if(null===a.match(/^[0-9]+$/))b=!1;else{var a=a.split("").reverse().join(""),c=0,d;for(b=0;b<a.length;++b)d=parseInt(a.charAt(b),10),0!=b%2&&(d*=2),c+=10>d?d:d-9;b=0!=c&&0==c%10}return b};c.cardType=function(a){if(!d){d={};for(var b=40;49>=b;++b)d[b]="Visa";for(b=50;59>=b;++b)d[b]="MasterCard";d[34]=d[37]="American Express";d[60]=d[62]=d[64]=d[65]="Discover";d[35]="JCB";d[30]=d[36]=d[38]=d[39]="Diners Club"}a=d[a.substr(0,
2)];return"undefined"===typeof a?"Unknown":a};c.validateCVC=function(a){a=j(a);return null!==a.match(/^[0-9]+$/)&&3<=a.length&&4>=a.length};c.validateExpiry=function(a,b){var a=j(a),b=j(b),c=new Date;return null!==a.match(/^[0-9]+$/)&&null!==b.match(/^[0-9]+$/)&&b>c.getFullYear()||b==c.getFullYear()&&a>=c.getMonth()+1};c.createToken=function(a,b,d){"function"===typeof b&&(d=b,b=null);m();var e={expMonth:"exp_month",expYear:"exp_year",addressLine1:"address_line_1",addressLine2:"address_line_2",addressZip:"address_zip",
addressState:"address_state",addressCountry:"address_country"};for(convertibleParam in e)e.hasOwnProperty(convertibleParam)&&a.hasOwnProperty(convertibleParam)&&(a[e[convertibleParam]]=a[convertibleParam],delete a[convertibleParam]);params={card:a};null!==b&&(params.amount=b);c.transport.callAPI("POST","tokens",params,c.publishableKey,d)};c.getToken=function(a,b){m();c.transport.callAPI("GET","tokens/"+a,{},c.publishableKey,b)};c.setPublishableKey=function(a){c.publishableKey=a};k.init()})("undefined"!==
typeof exports&&null!==exports?exports:window.Stripe={});
